name = "MyJuliaExamplePackage"
uuid = "18897a44-8413-4009-97af-20bb8bc4d1cf"
authors = ["Gerald E. Fux"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JET", "Test"]
